-- Add credit fields and size fields
ALTER TABLE "Model" ADD COLUMN IF NOT EXISTS "creditName" TEXT;
ALTER TABLE "Model" ADD COLUMN IF NOT EXISTS "creditUrl" TEXT;
ALTER TABLE "Model" ADD COLUMN IF NOT EXISTS "sizeXmm" DOUBLE PRECISION;
ALTER TABLE "Model" ADD COLUMN IF NOT EXISTS "sizeYmm" DOUBLE PRECISION;
ALTER TABLE "Model" ADD COLUMN IF NOT EXISTS "sizeZmm" DOUBLE PRECISION;

ALTER TABLE "ModelPart" ADD COLUMN IF NOT EXISTS "sizeXmm" DOUBLE PRECISION;
ALTER TABLE "ModelPart" ADD COLUMN IF NOT EXISTS "sizeYmm" DOUBLE PRECISION;
ALTER TABLE "ModelPart" ADD COLUMN IF NOT EXISTS "sizeZmm" DOUBLE PRECISION;
