ALTER TABLE "User"
  ADD COLUMN "discountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "isFriendsAndFamily" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "friendsAndFamilyPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
