CREATE TABLE IF NOT EXISTS "ModelPart" (
  "id" TEXT PRIMARY KEY,
  "modelId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "index" INTEGER NOT NULL DEFAULT 0,
  "filePath" TEXT NOT NULL,
  "volumeMm3" DOUBLE PRECISION,
  "priceUsd" DOUBLE PRECISION,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ModelPart_model_fkey" FOREIGN KEY ("modelId") REFERENCES "Model"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

